{{- if .Values.podDisruptionBudget.enabled }}
{{- $services := dict
  "task-dashboard" .Values.taskDashboard
  "task-enricher" .Values.taskEnricher
  "task-gateway" .Values.taskGateway
  "task-validator" .Values.taskValidator
-}}

{{- range $name, $config := $services }}
{{- if $config.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $name }}-pdb
spec:
  minAvailable: 2 # Always keep at least 2 pods during node drain
  selector:
    matchLabels:
      app: {{ $name }}
{{- end }}
{{- end }}
{{- end }}
