{{- $services := dict
  "task-dashboard" .Values.taskDashboard
  "task-enricher" .Values.taskEnricher
  "task-gateway" .Values.taskGateway
  "task-validator" .Values.taskValidator
-}}

{{- range $name, $config := $services }}
{{- if $config.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
spec:
  type: {{ $config.service.type }}

  ports:
    - port: {{ $config.service.port }}
      targetPort: {{ $config.service.targetPort }}
      protocol: TCP
      name: http

  selector:
    app: {{ $name }}
{{- end }}
{{- end }}
