# helm/microservices/Chart.yaml
apiVersion: v2
name: microservices
description: Enterprise polyglot microservices platform
type: application
version: 0.1.0
appVersion: "1.0.0"
icon: https://raw.githubusercontent.com/helm/helm/main/docs/images/helm.svg

keywords:
  - microservices
  - platform-engineering

maintainers:
  - name: Augustine N. Nkansah
    email: aankansah22@gmail.com
