version: "3.8"

services:
  frontend-app:
    build:
      context: ./frontend-app
      dockerfile: Dockerfile
    image: platform-frontend-app:latest
    ports:
      - "3000:80"
    restart: unless-stopped
